/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ee2606project_student2028016;

import java.time.LocalDate;
import java.time.Month;

/**
 *
 * @author Ayush Kumar [Student Number: 2028016]
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        
        CAddress = new IAddress();
        branches = new BranchList();
        Customers = new CustomerList();
        // Initialisation of HeadOfficeBranchAddress (IAddress):
        HeadOfficeBranchAddress = new IAddress();
        HeadOfficeBranchAddress.Edit("Smith","High Street",271,"Bank House","Mayfair","W1A 2BC","London","UK");
        // Initialisation of HeadOfficeBranch (Branch):
        HeadOfficeBranch = new Branch();
        HeadOfficeBranch.Edit("09:00 - 17:00","00-00-00","Manager");
        // Initialisation of NewCustomer (Person):
       /* NewCustomer = new Person();
        NewCustomer.Edit("Ayush","Kumar",LocalDate.of(2002,04,21),LocalDate.of(2020,10,13));*/
        // Initialisation of user (User):
        user = new User();
        // Initialisation of BranchAdress (IAddress):
        BranchAddress = new IAddress();
        BranchAddress.Edit("Smith","High Street",271,"Bank House","Mayfair","W1A 2BC","London","UK");
        // Initialisation of jTabInMemory(temporary object):
        jTabInMemory = jMainTabbedPane.getComponentAt(1); // The 'getComponentAt' methods called for the component at index 1; i.e., "Calculator"
        jMainTabbedPane.remove(1); // This helps remove the other tab from the jMainTabbedPane
        jMainTabbedPane.setSelectedIndex(0);
        // Initialisation of jTabInHeadOfficeMemory(temporary object):
        jTabInHeadOfficeMemory = jMainTabbedPane.getComponentAt(1);
        jMainTabbedPane.remove(1); // This helps remove the other tab from the jMainTabbedPane
        jMainTabbedPane.setSelectedIndex(0);
        // Initialisation of jTabInPersonMemory(temporary object):
        jTabInPersonMemory = jMainTabbedPane.getComponentAt(1);
        jMainTabbedPane.remove(1); // This helps remove the other tab from the jMainTabbedPane
        jMainTabbedPane.setSelectedIndex(0);
        // Initialisation of jTabInHeadEditOfficeMemory(temporary object):
        jTabInEditHeadOfficeMemory = jMainTabbedPane.getComponentAt(1);
        jMainTabbedPane.remove(1); // This helps remove the other tab from the jMainTabbedPane
        jMainTabbedPane.setSelectedIndex(0);
        // The following 'for-loop' extracts the name of a given tab to enable/disable based on its name and index:
        for (int index = 0; index < jMainTabbedPane.getTabCount(); index++)
        
        {
            if (!jMainTabbedPane.getTitleAt(index).contentEquals("Login"))
                jMainTabbedPane.setEnabledAt(index,true); // This has disabled the tab until logged in correctly
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel = new javax.swing.JPanel();
        jStatusMessageLabel = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jMainPanel = new javax.swing.JPanel();
        jMainTabbedPane = new javax.swing.JTabbedPane();
        jLoginPanel = new javax.swing.JPanel();
        jNameLabel = new javax.swing.JLabel();
        jNameField = new javax.swing.JTextField();
        jLoginButton = new javax.swing.JButton();
        jPasswordLabel = new javax.swing.JLabel();
        jPasswordTextField = new javax.swing.JTextField();
        jRoleComboBox = new javax.swing.JComboBox<>();
        jRegisterButton = new javax.swing.JButton();
        jCalculatorPanel = new javax.swing.JPanel();
        jInputLabel1 = new javax.swing.JLabel();
        jInputField1 = new javax.swing.JTextField();
        jInputLabel2 = new javax.swing.JLabel();
        jInputField2 = new javax.swing.JTextField();
        jOutputLabel = new javax.swing.JLabel();
        jOutputField = new javax.swing.JTextField();
        jSumButton = new javax.swing.JButton();
        jSubtractionButton = new javax.swing.JButton();
        jMultiplicationButton = new javax.swing.JButton();
        jDivisionButton = new javax.swing.JButton();
        jPowerButton = new javax.swing.JButton();
        jCylinderVolumeButton = new javax.swing.JButton();
        jSphereVolumeButton = new javax.swing.JButton();
        jSquarePyramidVolumeButton = new javax.swing.JButton();
        jHeadOfficePanel = new javax.swing.JPanel();
        jAddressPane = new javax.swing.JScrollPane();
        jHeadOfficeTextArea = new javax.swing.JTextArea();
        jDisplayButton = new javax.swing.JButton();
        jPersonPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPersonTextArea = new javax.swing.JTextArea();
        jGetInformationButton = new javax.swing.JButton();
        jDayTextField = new javax.swing.JTextField();
        jMonthTextField = new javax.swing.JTextField();
        jYearTextField = new javax.swing.JTextField();
        DD = new javax.swing.JLabel();
        MM = new javax.swing.JLabel();
        YYYY = new javax.swing.JLabel();
        jCheckDOBButton = new javax.swing.JButton();
        jEditHeadOfficePanel = new javax.swing.JPanel();
        jEditInstructionLabel = new javax.swing.JLabel();
        jEditNameLabel = new javax.swing.JLabel();
        jEditButton = new javax.swing.JButton();
        jEditStreetTextField = new javax.swing.JTextField();
        jEditStreetLabel = new javax.swing.JLabel();
        jEditNameTextField = new javax.swing.JTextField();
        jEditHouseNameLabel = new javax.swing.JLabel();
        jEditHouseNameTextField = new javax.swing.JTextField();
        jEditHouseNumberLabel = new javax.swing.JLabel();
        jEditHouseNumberTextField = new javax.swing.JTextField();
        jEditPostCodeLabel = new javax.swing.JLabel();
        jEditPostCodeTextField = new javax.swing.JTextField();
        jEditTownLabel = new javax.swing.JLabel();
        jEditTownTextField = new javax.swing.JTextField();
        jEditCountryLabel = new javax.swing.JLabel();
        jEditCountryTextField = new javax.swing.JTextField();
        jEditWorkingHoursLabel = new javax.swing.JLabel();
        jEditAreaTextField = new javax.swing.JTextField();
        jEditAreaLabel = new javax.swing.JLabel();
        jEditWorkingHoursTextField = new javax.swing.JTextField();
        jEditSortCodeLabel = new javax.swing.JLabel();
        jEditSortCodeTextField = new javax.swing.JTextField();
        jEditManagerLabel = new javax.swing.JLabel();
        jEditManagerTextField = new javax.swing.JTextField();
        jEditClientsPanel = new javax.swing.JPanel();
        jClientFNameTextField = new javax.swing.JTextField();
        jClientSNameTextField = new javax.swing.JTextField();
        jClientFNameLabel = new javax.swing.JLabel();
        jCLientSNameLabel = new javax.swing.JLabel();
        jClientDDLabel = new javax.swing.JLabel();
        jClientMMLabel = new javax.swing.JLabel();
        jClientYYYYLabel = new javax.swing.JLabel();
        jEditClientButton = new javax.swing.JButton();
        jEditDDTextField = new javax.swing.JTextField();
        jEditMMTextField = new javax.swing.JTextField();
        jEditYYYYTextField = new javax.swing.JTextField();
        jDOBLabel = new javax.swing.JLabel();
        jCSLabel = new javax.swing.JLabel();
        jEditCSDayTextField = new javax.swing.JTextField();
        jEditCSMonthTextField = new javax.swing.JTextField();
        jEditCSYearTextField = new javax.swing.JTextField();
        jClientHouseNumberTextField = new javax.swing.JTextField();
        jClientStreetTextField = new javax.swing.JTextField();
        jClientHouseNameTextField = new javax.swing.JTextField();
        jClientAreaTextField = new javax.swing.JTextField();
        jClientPostCodeTextField = new javax.swing.JTextField();
        jClientTownTextField = new javax.swing.JTextField();
        jClientCountryTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jClientsPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jDisplayClientTextArea = new javax.swing.JTextArea();
        jDisplayClientButton = new javax.swing.JButton();
        jSearchClientsButton = new javax.swing.JButton();
        jSearchFNameTextField = new javax.swing.JTextField();
        jSearchSNameTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jRemoveButton = new javax.swing.JButton();
        jAccountPanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jDisplayAccountTextArea = new javax.swing.JTextArea();
        jDisplayAccountButton = new javax.swing.JButton();
        jMainMenuBar = new javax.swing.JMenuBar();
        jFileMenu = new javax.swing.JMenu();
        jEditMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jStatusMessageLabel.setFont(new java.awt.Font("Helvetica Neue", 2, 13)); // NOI18N
        jStatusMessageLabel.setForeground(new java.awt.Color(102, 102, 102));
        jStatusMessageLabel.setText("Application is running succesfully...");

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jStatusMessageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jStatusMessageLabel))
                .addGap(40, 40, 40))
        );

        jNameLabel.setText("Please enter credentials:");
        jNameLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLoginButton.setText("Login");
        jLoginButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLoginButtonActionPerformed(evt);
            }
        });

        jPasswordLabel.setText("Enter password:");

        jRoleComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Employee", "Manager", "Client", "Advisor", "Administrator", " " }));

        jRegisterButton.setText("Register");
        jRegisterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRegisterButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jLoginPanelLayout = new javax.swing.GroupLayout(jLoginPanel);
        jLoginPanel.setLayout(jLoginPanelLayout);
        jLoginPanelLayout.setHorizontalGroup(
            jLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLoginPanelLayout.createSequentialGroup()
                .addGroup(jLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLoginPanelLayout.createSequentialGroup()
                        .addGap(232, 232, 232)
                        .addComponent(jNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLoginPanelLayout.createSequentialGroup()
                        .addGap(252, 252, 252)
                        .addComponent(jPasswordLabel)))
                .addGap(81, 81, 81)
                .addGroup(jLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jNameField, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(jPasswordTextField))
                .addContainerGap(145, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLoginPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRegisterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRoleComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(397, 397, 397))
        );
        jLoginPanelLayout.setVerticalGroup(
            jLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLoginPanelLayout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addGroup(jLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNameLabel)
                    .addComponent(jNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPasswordLabel)
                    .addComponent(jPasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jRoleComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLoginButton)
                .addGap(18, 18, 18)
                .addComponent(jRegisterButton)
                .addContainerGap(149, Short.MAX_VALUE))
        );

        jMainTabbedPane.addTab("Login", jLoginPanel);

        jInputLabel1.setText("Input 1:");

        jInputField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jInputField1ActionPerformed(evt);
            }
        });

        jInputLabel2.setText("Input 2:");

        jOutputLabel.setText("Output:");

        jSumButton.setText("+");
        jSumButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSumButtonActionPerformed(evt);
            }
        });

        jSubtractionButton.setText("-");
        jSubtractionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSubtractionButtonActionPerformed(evt);
            }
        });

        jMultiplicationButton.setText("×");
        jMultiplicationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMultiplicationButtonActionPerformed(evt);
            }
        });

        jDivisionButton.setText("÷");
        jDivisionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDivisionButtonActionPerformed(evt);
            }
        });

        jPowerButton.setText("Power");
        jPowerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPowerButtonActionPerformed(evt);
            }
        });

        jCylinderVolumeButton.setText("Cylinder Volume");
        jCylinderVolumeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCylinderVolumeButtonActionPerformed(evt);
            }
        });

        jSphereVolumeButton.setText("Sphere Volume");
        jSphereVolumeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSphereVolumeButtonActionPerformed(evt);
            }
        });

        jSquarePyramidVolumeButton.setText("Square Pyramid Volume");
        jSquarePyramidVolumeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSquarePyramidVolumeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jCalculatorPanelLayout = new javax.swing.GroupLayout(jCalculatorPanel);
        jCalculatorPanel.setLayout(jCalculatorPanelLayout);
        jCalculatorPanelLayout.setHorizontalGroup(
            jCalculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jCalculatorPanelLayout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addGroup(jCalculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jCalculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jCalculatorPanelLayout.createSequentialGroup()
                            .addComponent(jInputLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jInputField2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jCalculatorPanelLayout.createSequentialGroup()
                            .addComponent(jInputLabel1)
                            .addGap(94, 94, 94)
                            .addComponent(jInputField1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jCalculatorPanelLayout.createSequentialGroup()
                        .addComponent(jOutputLabel)
                        .addGap(18, 18, 18)
                        .addComponent(jOutputField, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(57, 57, 57)
                .addGroup(jCalculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jCalculatorPanelLayout.createSequentialGroup()
                        .addComponent(jSumButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jMultiplicationButton))
                    .addGroup(jCalculatorPanelLayout.createSequentialGroup()
                        .addComponent(jSphereVolumeButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPowerButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jCalculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jCalculatorPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jCalculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSquarePyramidVolumeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jCylinderVolumeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jCalculatorPanelLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jSubtractionButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jDivisionButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jCalculatorPanelLayout.setVerticalGroup(
            jCalculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jCalculatorPanelLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(jCalculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jInputLabel1)
                    .addComponent(jInputField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSumButton)
                    .addComponent(jSubtractionButton)
                    .addComponent(jMultiplicationButton)
                    .addComponent(jDivisionButton))
                .addGap(30, 30, 30)
                .addGroup(jCalculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jInputLabel2)
                    .addComponent(jInputField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPowerButton)
                    .addComponent(jCylinderVolumeButton))
                .addGap(28, 28, 28)
                .addGroup(jCalculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jOutputLabel)
                    .addComponent(jOutputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSphereVolumeButton)
                    .addComponent(jSquarePyramidVolumeButton))
                .addContainerGap(313, Short.MAX_VALUE))
        );

        jMainTabbedPane.addTab("Calculator", jCalculatorPanel);

        jHeadOfficeTextArea.setColumns(20);
        jHeadOfficeTextArea.setRows(5);
        jAddressPane.setViewportView(jHeadOfficeTextArea);

        jDisplayButton.setText("Display");
        jDisplayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDisplayButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jHeadOfficePanelLayout = new javax.swing.GroupLayout(jHeadOfficePanel);
        jHeadOfficePanel.setLayout(jHeadOfficePanelLayout);
        jHeadOfficePanelLayout.setHorizontalGroup(
            jHeadOfficePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jHeadOfficePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jAddressPane, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(172, 172, 172)
                .addComponent(jDisplayButton)
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jHeadOfficePanelLayout.setVerticalGroup(
            jHeadOfficePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jHeadOfficePanelLayout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addComponent(jDisplayButton)
                .addGap(0, 306, Short.MAX_VALUE))
            .addGroup(jHeadOfficePanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jAddressPane)
                .addContainerGap())
        );

        jMainTabbedPane.addTab("Head Office", jHeadOfficePanel);

        jPersonTextArea.setColumns(20);
        jPersonTextArea.setRows(5);
        jScrollPane1.setViewportView(jPersonTextArea);

        jGetInformationButton.setText("Get Information");
        jGetInformationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGetInformationButtonActionPerformed(evt);
            }
        });

        DD.setText("DD");

        MM.setText("MM");

        YYYY.setText("YYYY");

        jCheckDOBButton.setText("Check DOB");
        jCheckDOBButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckDOBButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPersonPanelLayout = new javax.swing.GroupLayout(jPersonPanel);
        jPersonPanel.setLayout(jPersonPanelLayout);
        jPersonPanelLayout.setHorizontalGroup(
            jPersonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPersonPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addGroup(jPersonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(DD)
                    .addComponent(MM)
                    .addComponent(YYYY))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPersonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jCheckDOBButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jGetInformationButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jDayTextField)
                    .addComponent(jMonthTextField)
                    .addComponent(jYearTextField))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPersonPanelLayout.setVerticalGroup(
            jPersonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPersonPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1)
                .addGap(14, 14, 14))
            .addGroup(jPersonPanelLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jGetInformationButton)
                .addGap(47, 47, 47)
                .addGroup(jPersonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jDayTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DD))
                .addGap(35, 35, 35)
                .addGroup(jPersonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jMonthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MM))
                .addGap(32, 32, 32)
                .addGroup(jPersonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jYearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(YYYY))
                .addGap(35, 35, 35)
                .addComponent(jCheckDOBButton)
                .addContainerGap(177, Short.MAX_VALUE))
        );

        jMainTabbedPane.addTab("Person", jPersonPanel);

        jEditInstructionLabel.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jEditInstructionLabel.setText("To make changes to the fields that are mentioned below, please enter new values and click on Edit.");

        jEditNameLabel.setText("Name:");

        jEditButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jEditButton.setText("Edit");
        jEditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEditButtonActionPerformed(evt);
            }
        });

        jEditStreetTextField.setText(" ");

        jEditStreetLabel.setText("Street:");

        jEditNameTextField.setText(" ");
        jEditNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEditNameTextFieldActionPerformed(evt);
            }
        });

        jEditHouseNameLabel.setText("House Name:");

        jEditHouseNameTextField.setText(" ");

        jEditHouseNumberLabel.setText("House Number:");

        jEditHouseNumberTextField.setText(" ");

        jEditPostCodeLabel.setText("Post Code:");

        jEditPostCodeTextField.setText(" ");

        jEditTownLabel.setText("Town:");

        jEditTownTextField.setText(" ");

        jEditCountryLabel.setText("Country:");

        jEditWorkingHoursLabel.setText("Working Hours:");

        jEditAreaTextField.setText(" ");

        jEditAreaLabel.setText("Area:");

        jEditSortCodeLabel.setText("Sort Code:");

        jEditManagerLabel.setText("Manager");

        javax.swing.GroupLayout jEditHeadOfficePanelLayout = new javax.swing.GroupLayout(jEditHeadOfficePanel);
        jEditHeadOfficePanel.setLayout(jEditHeadOfficePanelLayout);
        jEditHeadOfficePanelLayout.setHorizontalGroup(
            jEditHeadOfficePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jEditHeadOfficePanelLayout.createSequentialGroup()
                .addGroup(jEditHeadOfficePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jEditHeadOfficePanelLayout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(jEditInstructionLabel))
                    .addGroup(jEditHeadOfficePanelLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(jEditHeadOfficePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jEditHouseNameLabel)
                            .addComponent(jEditHouseNumberLabel)
                            .addComponent(jEditPostCodeLabel)
                            .addGroup(jEditHeadOfficePanelLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jEditNameLabel))
                            .addComponent(jEditTownLabel)
                            .addComponent(jEditStreetLabel)
                            .addComponent(jEditCountryLabel)
                            .addComponent(jEditAreaLabel))
                        .addGap(25, 25, 25)
                        .addGroup(jEditHeadOfficePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jEditPostCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jEditHeadOfficePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jEditCountryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jEditTownTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jEditHouseNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jEditHeadOfficePanelLayout.createSequentialGroup()
                                    .addComponent(jEditAreaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jEditButton)
                                    .addGap(151, 151, 151))
                                .addComponent(jEditHouseNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jEditHeadOfficePanelLayout.createSequentialGroup()
                                    .addGroup(jEditHeadOfficePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jEditStreetTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jEditNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(74, 74, 74)
                                    .addGroup(jEditHeadOfficePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jEditWorkingHoursLabel)
                                        .addComponent(jEditManagerLabel))
                                    .addGap(39, 39, 39)
                                    .addGroup(jEditHeadOfficePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jEditHeadOfficePanelLayout.createSequentialGroup()
                                            .addComponent(jEditManagerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(91, 91, 91)
                                            .addComponent(jEditSortCodeLabel)
                                            .addGap(34, 34, 34)
                                            .addComponent(jEditSortCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jEditWorkingHoursTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jEditHeadOfficePanelLayout.setVerticalGroup(
            jEditHeadOfficePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jEditHeadOfficePanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jEditInstructionLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jEditHeadOfficePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jEditNameLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jEditHeadOfficePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jEditNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jEditSortCodeLabel)
                        .addComponent(jEditSortCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jEditManagerLabel)
                        .addComponent(jEditManagerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jEditHeadOfficePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jEditStreetLabel)
                    .addComponent(jEditStreetTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jEditWorkingHoursLabel)
                    .addComponent(jEditWorkingHoursTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jEditHeadOfficePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jEditHouseNameLabel)
                    .addComponent(jEditHouseNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jEditHeadOfficePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jEditHouseNumberLabel)
                    .addComponent(jEditHouseNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jEditHeadOfficePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jEditButton)
                    .addComponent(jEditAreaLabel)
                    .addComponent(jEditAreaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jEditHeadOfficePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jEditPostCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jEditPostCodeLabel))
                .addGap(14, 14, 14)
                .addGroup(jEditHeadOfficePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jEditTownLabel)
                    .addComponent(jEditTownTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jEditHeadOfficePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jEditCountryLabel)
                    .addComponent(jEditCountryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(122, 122, 122))
        );

        jMainTabbedPane.addTab("Edit Head Office", jEditHeadOfficePanel);

        jClientFNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jClientFNameTextFieldActionPerformed(evt);
            }
        });

        jClientFNameLabel.setText("Firstname");

        jCLientSNameLabel.setText("Surname");

        jClientDDLabel.setText("DD");

        jClientMMLabel.setText("MM");

        jClientYYYYLabel.setText("YYYY");

        jEditClientButton.setText("Save");
        jEditClientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEditClientButtonActionPerformed(evt);
            }
        });

        jDOBLabel.setText("Date of Birth");

        jCSLabel.setText("Customer SInce");

        jEditCSDayTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEditCSDayTextFieldActionPerformed(evt);
            }
        });

        jEditCSYearTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEditCSYearTextFieldActionPerformed(evt);
            }
        });

        jLabel3.setText("House number");

        jLabel4.setText("Street");

        jLabel5.setText("Area");

        jLabel6.setText("Post Code");

        jLabel7.setText("Town");

        jLabel8.setText("Country");

        jLabel9.setText("House name");

        javax.swing.GroupLayout jEditClientsPanelLayout = new javax.swing.GroupLayout(jEditClientsPanel);
        jEditClientsPanel.setLayout(jEditClientsPanelLayout);
        jEditClientsPanelLayout.setHorizontalGroup(
            jEditClientsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jEditClientsPanelLayout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addGroup(jEditClientsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jClientYYYYLabel)
                    .addGroup(jEditClientsPanelLayout.createSequentialGroup()
                        .addGroup(jEditClientsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jClientMMLabel)
                            .addComponent(jClientDDLabel))
                        .addGap(86, 86, 86)
                        .addGroup(jEditClientsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jEditClientsPanelLayout.createSequentialGroup()
                                .addGroup(jEditClientsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jEditDDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jEditMMTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jEditYYYYTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(44, 44, 44)
                                .addGroup(jEditClientsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jEditCSDayTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jEditCSMonthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCSLabel)
                                    .addComponent(jEditCSYearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jEditClientsPanelLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(jEditClientsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jDOBLabel)
                                    .addGroup(jEditClientsPanelLayout.createSequentialGroup()
                                        .addGroup(jEditClientsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jClientFNameLabel)
                                            .addComponent(jCLientSNameLabel))
                                        .addGap(27, 27, 27)
                                        .addGroup(jEditClientsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jClientSNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jClientFNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(77, 77, 77)
                        .addGroup(jEditClientsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addGap(62, 62, 62)
                        .addGroup(jEditClientsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jClientStreetTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jClientHouseNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jClientHouseNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jClientAreaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jClientPostCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jClientTownTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jClientCountryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jEditClientsPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jEditClientButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(380, 380, 380))
        );
        jEditClientsPanelLayout.setVerticalGroup(
            jEditClientsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jEditClientsPanelLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jEditClientsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jEditClientsPanelLayout.createSequentialGroup()
                        .addGroup(jEditClientsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jClientFNameLabel)
                            .addComponent(jClientFNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(jEditClientsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jClientSNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCLientSNameLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jEditClientsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCSLabel)
                            .addComponent(jDOBLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jEditClientsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jEditDDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jClientDDLabel)
                            .addComponent(jEditCSDayTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jEditClientsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jEditMMTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jEditCSMonthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jClientMMLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jEditClientsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jEditClientsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jEditYYYYTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jClientYYYYLabel))
                            .addComponent(jEditCSYearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(93, 93, 93)
                        .addComponent(jEditClientButton)
                        .addGap(173, 173, 173))
                    .addGroup(jEditClientsPanelLayout.createSequentialGroup()
                        .addGroup(jEditClientsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jClientHouseNumberTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jEditClientsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jClientStreetTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jEditClientsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jClientAreaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(9, 9, 9)
                        .addGroup(jEditClientsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jClientPostCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jEditClientsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jClientTownTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jEditClientsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jClientCountryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jEditClientsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jClientHouseNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jMainTabbedPane.addTab("Edit Clients", jEditClientsPanel);

        jDisplayClientTextArea.setColumns(20);
        jDisplayClientTextArea.setRows(5);
        jScrollPane2.setViewportView(jDisplayClientTextArea);

        jDisplayClientButton.setText("Display");
        jDisplayClientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDisplayClientButtonActionPerformed(evt);
            }
        });

        jSearchClientsButton.setText("Search");
        jSearchClientsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSearchClientsButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Firstname");

        jLabel2.setText("Surname");

        jRemoveButton.setText("Remove");
        jRemoveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRemoveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jClientsPanelLayout = new javax.swing.GroupLayout(jClientsPanel);
        jClientsPanel.setLayout(jClientsPanelLayout);
        jClientsPanelLayout.setHorizontalGroup(
            jClientsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jClientsPanelLayout.createSequentialGroup()
                .addGroup(jClientsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jClientsPanelLayout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jClientsPanelLayout.createSequentialGroup()
                        .addGap(354, 354, 354)
                        .addComponent(jLabel1))
                    .addGroup(jClientsPanelLayout.createSequentialGroup()
                        .addGroup(jClientsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jClientsPanelLayout.createSequentialGroup()
                                .addGap(331, 331, 331)
                                .addGroup(jClientsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSearchFNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSearchSNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jClientsPanelLayout.createSequentialGroup()
                                .addGap(204, 204, 204)
                                .addComponent(jDisplayClientButton)
                                .addGap(79, 79, 79)
                                .addComponent(jLabel2)))
                        .addGap(29, 29, 29)
                        .addGroup(jClientsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSearchClientsButton)
                            .addComponent(jRemoveButton))))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        jClientsPanelLayout.setVerticalGroup(
            jClientsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jClientsPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jClientsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jClientsPanelLayout.createSequentialGroup()
                        .addComponent(jSearchFNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jClientsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jDisplayClientButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSearchSNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65))
                    .addGroup(jClientsPanelLayout.createSequentialGroup()
                        .addComponent(jSearchClientsButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRemoveButton)
                        .addGap(85, 85, 85))))
        );

        jMainTabbedPane.addTab("Clients", jClientsPanel);

        jDisplayAccountTextArea.setColumns(20);
        jDisplayAccountTextArea.setRows(5);
        jScrollPane3.setViewportView(jDisplayAccountTextArea);

        jDisplayAccountButton.setText("Display");

        javax.swing.GroupLayout jAccountPanelLayout = new javax.swing.GroupLayout(jAccountPanel);
        jAccountPanel.setLayout(jAccountPanelLayout);
        jAccountPanelLayout.setHorizontalGroup(
            jAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jAccountPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jAccountPanelLayout.createSequentialGroup()
                .addContainerGap(360, Short.MAX_VALUE)
                .addComponent(jDisplayAccountButton)
                .addGap(331, 331, 331))
        );
        jAccountPanelLayout.setVerticalGroup(
            jAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jAccountPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jDisplayAccountButton)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        jMainTabbedPane.addTab("Account", jAccountPanel);

        javax.swing.GroupLayout jMainPanelLayout = new javax.swing.GroupLayout(jMainPanel);
        jMainPanel.setLayout(jMainPanelLayout);
        jMainPanelLayout.setHorizontalGroup(
            jMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jMainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jMainTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 763, Short.MAX_VALUE)
                .addContainerGap())
        );
        jMainPanelLayout.setVerticalGroup(
            jMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jMainPanelLayout.createSequentialGroup()
                .addComponent(jMainTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        jFileMenu.setText("File");
        jMainMenuBar.add(jFileMenu);

        jEditMenu.setText("Edit");
        jMainMenuBar.add(jEditMenu);

        setJMenuBar(jMainMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jMainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 534, Short.MAX_VALUE)
                .addComponent(jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jMainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 25, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckDOBButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckDOBButtonActionPerformed
        // TODO add your handling code here:
        if(CheckDOB()){
            int DayInput = Integer.valueOf(jDayTextField.getText());
            int MonthInput = Integer.valueOf(jMonthTextField.getText());
            int YearInput = Integer.valueOf(jYearTextField.getText());

            LocalDate DOBInput = LocalDate.of(YearInput,MonthInput,DayInput);

            if(DOBInput.equals(NewCustomer.DOB)==true){

                jPersonTextArea.setText("CONFIRMED: ");
                NewCustomer.Display(jPersonTextArea);

            }else{

                jPersonTextArea.setText("Incorrect.");
            }
        }

    }//GEN-LAST:event_jCheckDOBButtonActionPerformed

    private void jGetInformationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGetInformationButtonActionPerformed
        // The following line displays the the information about the User:
        NewCustomer.Display(jPersonTextArea);
    }//GEN-LAST:event_jGetInformationButtonActionPerformed

    private void jDisplayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDisplayButtonActionPerformed
        // Display button to show head office address:
        HeadOfficeBranch.Display(jHeadOfficeTextArea);//This displays the address
    }//GEN-LAST:event_jDisplayButtonActionPerformed

    private void jSquarePyramidVolumeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSquarePyramidVolumeButtonActionPerformed
        if(InputVerification()){
            // The following lines extract the user inputs and saved them to the memory:
            double input_1 = Double.valueOf(jInputField1.getText());// Radius input
            double input_2 = Double.valueOf(jInputField2.getText());// Height input
            // This performs the calculation to find the volume of the sqaure base pyramid:
            double output = power(input_1,2) * (input_2/3); // Volume of sqaure base pyramid is "square_base_area * height/3"
            // This provides the output in the text field:
            jOutputField.setText(String.valueOf(String.format("%.4f", output)));
        }
        else{
            jOutputField.setText("Invalid Input type detected!");
        }
    }//GEN-LAST:event_jSquarePyramidVolumeButtonActionPerformed

    private void jSphereVolumeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSphereVolumeButtonActionPerformed
        if(InputVerification()){
            // The following lines extract the user inputs and saved them to the memory:
            double input_1 = Double.valueOf(jInputField1.getText());// Radius input
            // This performs the calculation to find the volume of the sphere:
            double output = (1.3334) * (3.1415) * power(input_1,3); // volume of sphere is "4/3 * pi * radius^3"
            // This provides the ouput in the text field:
            jOutputField.setText(String.valueOf(String.format("%.4f", output)));
        }
        else{
            jOutputField.setText("Invalid Input type detected!");
        }
    }//GEN-LAST:event_jSphereVolumeButtonActionPerformed

    private void jCylinderVolumeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCylinderVolumeButtonActionPerformed
        if(InputVerification()){
            // The following lines extract the user inputs and saved them to the memory:
            double input_1 = Double.valueOf(jInputField1.getText());// Radius input
            double input_2 = Double.valueOf(jInputField2.getText());// Height input
            // This performs the calculation to find the volume of the cylinder:
            double output = (3.1415) * power(input_1,2) * input_2; // volume of cylinder is "pi * radius^2 * height". Pi is to 2 significant figures
            // This provides the ouput in the text field:
            jOutputField.setText(String.valueOf(String.format("%.4f", output)));
        }
        else{
            jOutputField.setText("Invalid Input type detected!");
        }
    }//GEN-LAST:event_jCylinderVolumeButtonActionPerformed

    private void jPowerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPowerButtonActionPerformed
        if(InputVerification()){
            // The following lines extract the user inputs and saved them to the memory:
            double input_1 = Double.valueOf(jInputField1.getText());
            double input_2 = Double.valueOf(jInputField2.getText());
            // This performs the exponential arithmetics using a prevoiusly created power method:
            double output = power(input_1,input_2);// Power method implementation
            jOutputField.setText(String.valueOf(String.format("%.4f", output)));// This provides the ouput in the text field:
        }
        else{
            jOutputField.setText("Invalid Input type detected!");
        }
    }//GEN-LAST:event_jPowerButtonActionPerformed

    private void jDivisionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDivisionButtonActionPerformed
        if(InputVerification()){
            // The following lines extract the user inputs and saved them to the memory:
            double input_1 = Double.valueOf(jInputField1.getText());
            double input_2 = Double.valueOf(jInputField2.getText());
            if (input_1 == 0 || input_2 == 0) {
                jOutputField.setText(String.valueOf("Math error: Cannot divide a number by 0!"));
            } else {
                // This performs the division:
                double output = input_1 / input_2;
                // This provides the ouput in the text field:
                jOutputField.setText(String.valueOf(String.format("%.4f", output)));}
        }
        else{
            jOutputField.setText("Invalid Input type detected!");
        }

    }//GEN-LAST:event_jDivisionButtonActionPerformed

    private void jMultiplicationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMultiplicationButtonActionPerformed
        if(InputVerification()){
            // The following lines extract the user inputs and saved them to the memory:
            double input_1 = Double.valueOf(jInputField1.getText());
            double input_2 = Double.valueOf(jInputField2.getText());
            // This performs the multiplication:
            double output = input_1 * input_2;
            jOutputField.setText(String.valueOf(String.format("%.4f", output)));
        }
        else{
            // This provides the ouput in the text field:
            jOutputField.setText("Invalid Input type detected!");
        }
    }//GEN-LAST:event_jMultiplicationButtonActionPerformed

    private void jSubtractionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSubtractionButtonActionPerformed
        if(InputVerification()){
            // The following lines extract the user inputs and saved them to the memory:
            double input_1 = Double.valueOf(jInputField1.getText());
            double input_2 = Double.valueOf(jInputField2.getText());
            // This performs the subtraction:
            double output = input_1 - input_2;
            jOutputField.setText(String.valueOf(String.format("%.4f", output)));
        }
        else{
            // This provides the ouput in the text field:
            jOutputField.setText("Invalid Input type detected!");
        }
    }//GEN-LAST:event_jSubtractionButtonActionPerformed

    private void jSumButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSumButtonActionPerformed
        if(InputVerification()){
            // The following lines extract the user inputs and saved them to the memory:
            double input_1 = Double.valueOf(jInputField1.getText());
            double input_2 = Double.valueOf(jInputField2.getText());
            // This performs the addition:
            double output = input_1 + input_2;
            jOutputField.setText(String.valueOf(String.format("%.4f", output)));
        }
        else{
            // This provides the output in the text field:
            jOutputField.setText("Invalid Input type detected!");
        }
    }//GEN-LAST:event_jSumButtonActionPerformed

    private void jInputField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jInputField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jInputField1ActionPerformed

    private void jLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLoginButtonActionPerformed
        /** 
         * The following is the login button's function, this button checks the credentials of the users
         * and cross-checks the same with a file in the project directory called "Login.txt" for all user scenarios.
         * 
         * It also manipulates the tab for the user based on their role that is selected from the rolebox drop-down menu.
         **/
        
        jStatusMessageLabel.setText(jNameField.getText() + " is logged in.");
        if(user.isUser(jNameField.getText(), jPasswordTextField.getText(),(String)jRoleComboBox.getSelectedItem())){
            String Role = user.RoleVerification(jNameField.getText(),jPasswordTextField.getText(), (String)jRoleComboBox.getSelectedItem());
            
            switch (Role){
                case "Employee": // This the tab manipulaton for Employee, once they have logged in.
                    jMainTabbedPane.addTab("Calculator", jTabInMemory);
                    jMainTabbedPane.addTab("Head Office", jTabInHeadOfficeMemory);
                    break;
                    
                case "Manager": // This the tab manipulaton for Manager, once they have logged in.
                    jMainTabbedPane.addTab("Calculator", jTabInMemory);
                    jMainTabbedPane.addTab("Head Office", jTabInHeadOfficeMemory);
                    jMainTabbedPane.addTab("Person", jTabInPersonMemory);
                    jMainTabbedPane.addTab("Edit Head Office", jTabInEditHeadOfficeMemory);
                    break;
                    
                case "Client": // This the tab manipulaton for Client, once they have logged in.
                    jMainTabbedPane.addTab("Calculator", jTabInMemory);
                    break;
                    
                case "Advisor": // This the tab manipulaton for Advisor, once they have logged in.
                    jMainTabbedPane.addTab("Calculator", jTabInMemory);
                    jMainTabbedPane.addTab("Head Office", jTabInHeadOfficeMemory);
                    jMainTabbedPane.addTab("Person", jTabInPersonMemory);
                    break;
                    
                case "Administrator": // This the tab manipulaton for Administrator, once they have logged in.
                    jMainTabbedPane.addTab("Calculator", jTabInMemory);
                    jMainTabbedPane.addTab("Head Office", jTabInHeadOfficeMemory);
                    jMainTabbedPane.addTab("Person", jTabInPersonMemory);
                    break;
            }
        }
        jMainTabbedPane.setSelectedIndex(0);
    }//GEN-LAST:event_jLoginButtonActionPerformed

    private void jEditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEditButtonActionPerformed
        // This is the activation code for the infromation to be edited based on the user input:
        Branch abranch = new Branch();
        IAddress HeadOfficeBranchAddress = new IAddress();
        
        BranchAddress.Edit(jEditNameTextField.getText(),jEditStreetTextField.getText(),Integer.valueOf(jEditHouseNumberTextField.getText()),
                jEditHouseNameTextField.getText(),jEditAreaTextField.getText(),jEditPostCodeTextField.getText(),jEditTownTextField.getText(),jEditCountryTextField.getText());
        
        abranch.Edit(jEditManagerTextField.getText(),jEditWorkingHoursTextField.getText(),jEditSortCodeTextField.getText());
        
        HeadOfficeBranch = abranch;
        HeadOfficeBranchAddress = BranchAddress;
        HeadOfficeBranch.SaveToFile(false);
    }//GEN-LAST:event_jEditButtonActionPerformed

    private void jRegisterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRegisterButtonActionPerformed
        // This registers the user and assigns them space in the "Login.txt" file:
        if(!user.isRegistered(jNameField.getText(), jPasswordTextField.getText(), (String)jRoleComboBox.getSelectedItem())){
            jStatusMessageLabel.setText("You can't be Registered");
        }else{
            jStatusMessageLabel.setText("You have been Registered");
        }
    }//GEN-LAST:event_jRegisterButtonActionPerformed

    private void jEditNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEditNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jEditNameTextFieldActionPerformed

    private void jClientFNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jClientFNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jClientFNameTextFieldActionPerformed

    private void jDisplayClientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDisplayClientButtonActionPerformed
        Customers.Display(jDisplayClientTextArea);
    }//GEN-LAST:event_jDisplayClientButtonActionPerformed

    private void jEditClientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEditClientButtonActionPerformed
        // TODO add your handling code here:
        IAddress CAddress = new IAddress();
        String DayInput = String.valueOf(jEditDDTextField.getText());
        String MonthInput = String.valueOf(jEditMMTextField.getText());
        String YearInput = String.valueOf(jEditYYYYTextField.getText());

        LocalDate DOBInput = LocalDate.of(Integer.parseInt(YearInput),Integer.parseInt(MonthInput),Integer.parseInt(DayInput));
        
        String CSdayInput = String.valueOf(jEditCSDayTextField.getText());
        String CSmonthInput = String.valueOf(jEditCSMonthTextField.getText());
        String CSyearInput = String.valueOf(jEditCSYearTextField.getText());
        
        LocalDate CSInput = LocalDate.of(Integer.parseInt(CSyearInput), Integer.parseInt(CSmonthInput),Integer.parseInt(CSdayInput));
        
        String Name = String.valueOf(jClientFNameTextField.getText())+String.valueOf(jClientSNameTextField.getText());
        
        CAddress.Edit(Name,String.valueOf(jClientStreetTextField.getText()),Integer.parseInt(jClientHouseNumberTextField.getText()),
                String.valueOf(jClientHouseNameTextField.getText()),String.valueOf(jClientAreaTextField.getText()),
                String.valueOf(jClientPostCodeTextField.getText()),String.valueOf(jClientTownTextField.getText()),
                String.valueOf(jClientCountryTextField.getText()));
        
        Person Cus = new Person(jClientFNameTextField.getText(),jClientSNameTextField.getText(),DOBInput, CSInput, CAddress);
        Cus.savetofile(true);
        
        
    }//GEN-LAST:event_jEditClientButtonActionPerformed

    private void jEditCSDayTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEditCSDayTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jEditCSDayTextFieldActionPerformed

    private void jEditCSYearTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEditCSYearTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jEditCSYearTextFieldActionPerformed

    private void jSearchClientsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSearchClientsButtonActionPerformed
        // TODO add your handling code here:
        String FindFName = jSearchFNameTextField.getText();
        String FindSName = jSearchSNameTextField.getText();
        
        Customers.search(FindFName,FindSName,jDisplayClientTextArea);
    }//GEN-LAST:event_jSearchClientsButtonActionPerformed

    private void jRemoveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRemoveButtonActionPerformed
        // TODO add your handling code here:
        String RemoveFName = jSearchFNameTextField.getText();
        String RemoveSName = jSearchSNameTextField.getText();
        //System.out.println(RemoveFName+RemoveSName);
        Customers.remove(RemoveFName, RemoveSName);
        jDisplayClientTextArea.setText("Customer Removed");
    }//GEN-LAST:event_jRemoveButtonActionPerformed

    // The verification method to see if the input type is valid or not:
    private boolean InputVerification(){
        try {
                double input_1 = Double.valueOf(jInputField1.getText());
                double input_2 = Double.valueOf(jInputField2.getText());
                return true;}
        catch (Exception e){
            return false;
        }
    }
    
    // The following is the custom made power method using a "for-loop":    
    public static double power (double x, double y){
        double result = x; // The values are kept in double to retain accuracy
        
        for (int i = 1; i < y; i++ ){
            result = result * x; // For loop to iterate the multiplication based on the exponent
        }
        return result;
    }
    
    public boolean CheckDOB(){
    
        try{
            int DayInput = Integer.valueOf(jDayTextField.getText());
            int MonthInput = Integer.valueOf(jMonthTextField.getText());
            int YearInput = Integer.valueOf(jYearTextField.getText());
            
            return true;
        }catch(Exception e){
            return false;
        }
        
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Manual decleration of the objects
    private java.awt.Component jTabInMemory;
    private java.awt.Component jTabInHeadOfficeMemory;
    private java.awt.Component jTabInPersonMemory;
    private java.awt.Component jTabInEditHeadOfficeMemory;
    private Branch HeadOfficeBranch;
    private Person NewCustomer;
    private IAddress HeadOfficeBranchAddress;
    private IAddress BranchAddress;
    private User user;
    private Branch LoadFile;
    private Person Client;
    private BranchList branches;
    private CustomerList Customers;
    private IAddress CAddress;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DD;
    private javax.swing.JLabel MM;
    private javax.swing.JLabel YYYY;
    private javax.swing.JPanel jAccountPanel;
    private javax.swing.JScrollPane jAddressPane;
    private javax.swing.JLabel jCLientSNameLabel;
    private javax.swing.JLabel jCSLabel;
    private javax.swing.JPanel jCalculatorPanel;
    private javax.swing.JButton jCheckDOBButton;
    private javax.swing.JTextField jClientAreaTextField;
    private javax.swing.JTextField jClientCountryTextField;
    private javax.swing.JLabel jClientDDLabel;
    private javax.swing.JLabel jClientFNameLabel;
    private javax.swing.JTextField jClientFNameTextField;
    private javax.swing.JTextField jClientHouseNameTextField;
    private javax.swing.JTextField jClientHouseNumberTextField;
    private javax.swing.JLabel jClientMMLabel;
    private javax.swing.JTextField jClientPostCodeTextField;
    private javax.swing.JTextField jClientSNameTextField;
    private javax.swing.JTextField jClientStreetTextField;
    private javax.swing.JTextField jClientTownTextField;
    private javax.swing.JLabel jClientYYYYLabel;
    private javax.swing.JPanel jClientsPanel;
    private javax.swing.JButton jCylinderVolumeButton;
    private javax.swing.JLabel jDOBLabel;
    private javax.swing.JTextField jDayTextField;
    private javax.swing.JButton jDisplayAccountButton;
    private javax.swing.JTextArea jDisplayAccountTextArea;
    private javax.swing.JButton jDisplayButton;
    private javax.swing.JButton jDisplayClientButton;
    private javax.swing.JTextArea jDisplayClientTextArea;
    private javax.swing.JButton jDivisionButton;
    private javax.swing.JLabel jEditAreaLabel;
    private javax.swing.JTextField jEditAreaTextField;
    private javax.swing.JButton jEditButton;
    private javax.swing.JTextField jEditCSDayTextField;
    private javax.swing.JTextField jEditCSMonthTextField;
    private javax.swing.JTextField jEditCSYearTextField;
    private javax.swing.JButton jEditClientButton;
    private javax.swing.JPanel jEditClientsPanel;
    private javax.swing.JLabel jEditCountryLabel;
    private javax.swing.JTextField jEditCountryTextField;
    private javax.swing.JTextField jEditDDTextField;
    private javax.swing.JPanel jEditHeadOfficePanel;
    private javax.swing.JLabel jEditHouseNameLabel;
    private javax.swing.JTextField jEditHouseNameTextField;
    private javax.swing.JLabel jEditHouseNumberLabel;
    private javax.swing.JTextField jEditHouseNumberTextField;
    private javax.swing.JLabel jEditInstructionLabel;
    private javax.swing.JTextField jEditMMTextField;
    private javax.swing.JLabel jEditManagerLabel;
    private javax.swing.JTextField jEditManagerTextField;
    private javax.swing.JMenu jEditMenu;
    private javax.swing.JLabel jEditNameLabel;
    private javax.swing.JTextField jEditNameTextField;
    private javax.swing.JLabel jEditPostCodeLabel;
    private javax.swing.JTextField jEditPostCodeTextField;
    private javax.swing.JLabel jEditSortCodeLabel;
    private javax.swing.JTextField jEditSortCodeTextField;
    private javax.swing.JLabel jEditStreetLabel;
    private javax.swing.JTextField jEditStreetTextField;
    private javax.swing.JLabel jEditTownLabel;
    private javax.swing.JTextField jEditTownTextField;
    private javax.swing.JLabel jEditWorkingHoursLabel;
    private javax.swing.JTextField jEditWorkingHoursTextField;
    private javax.swing.JTextField jEditYYYYTextField;
    private javax.swing.JMenu jFileMenu;
    private javax.swing.JButton jGetInformationButton;
    private javax.swing.JPanel jHeadOfficePanel;
    private javax.swing.JTextArea jHeadOfficeTextArea;
    private javax.swing.JTextField jInputField1;
    private javax.swing.JTextField jInputField2;
    private javax.swing.JLabel jInputLabel1;
    private javax.swing.JLabel jInputLabel2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton jLoginButton;
    private javax.swing.JPanel jLoginPanel;
    private javax.swing.JMenuBar jMainMenuBar;
    private javax.swing.JPanel jMainPanel;
    private javax.swing.JTabbedPane jMainTabbedPane;
    private javax.swing.JTextField jMonthTextField;
    private javax.swing.JButton jMultiplicationButton;
    private javax.swing.JTextField jNameField;
    private javax.swing.JLabel jNameLabel;
    private javax.swing.JTextField jOutputField;
    private javax.swing.JLabel jOutputLabel;
    private javax.swing.JPanel jPanel;
    private javax.swing.JLabel jPasswordLabel;
    private javax.swing.JTextField jPasswordTextField;
    private javax.swing.JPanel jPersonPanel;
    private javax.swing.JTextArea jPersonTextArea;
    private javax.swing.JButton jPowerButton;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JButton jRegisterButton;
    private javax.swing.JButton jRemoveButton;
    private javax.swing.JComboBox<String> jRoleComboBox;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton jSearchClientsButton;
    private javax.swing.JTextField jSearchFNameTextField;
    private javax.swing.JTextField jSearchSNameTextField;
    private javax.swing.JButton jSphereVolumeButton;
    private javax.swing.JButton jSquarePyramidVolumeButton;
    private javax.swing.JLabel jStatusMessageLabel;
    private javax.swing.JButton jSubtractionButton;
    private javax.swing.JButton jSumButton;
    private javax.swing.JTextField jYearTextField;
    // End of variables declaration//GEN-END:variables
}